services : 
  postgres :
    image : postgres:16-alpine
    environment : 
      POSTGRES_USER : ${DB_USER}
      POSTGRES_PASSWORD : ${DB_PASSWORD}
      POSTGRES_DB : ${DB_NAME}
    restart : unless-stopped
    env_file : 
      - .env
    networks : 
      - bot-network
    volumes :
      - postgres-data:/var/lib/postgresql/data

  bot :
    build : .
    depends_on :
      - postgres
    networks :
      - bot-network

networks :
  bot-network :
    driver : bridge

volumes :
  postgres-data :